import type { Metadata } from "next";
import "./globals.css";
import { CountriesProvider } from "@/context/countriesProvider";
import Header from "@/components/Header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
            <CountriesProvider>
                <body
                    className="bg-Light-Mode-Background dark:bg-Dark-Mode-Background text-Light-Mode-Text 
                        dark:text-white relative font-Nunito
                    "
                >
                    <Header/>
                    {children}
                </body>
            </CountriesProvider>
        </html>
    );
}
